/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carlosrivera_lab.pkg5;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Usuario Dell
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        eliminar = new javax.swing.JPopupMenu();
        elimiar_restaurante = new javax.swing.JMenuItem();
        eliminar_canchas = new javax.swing.JMenuItem();
        eliminar_carreteras = new javax.swing.JMenuItem();
        tab_principal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tab_lugares = new javax.swing.JTabbedPane();
        lugares = new javax.swing.JPanel();
        lugares_tab = new javax.swing.JTabbedPane();
        restaurante = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nombre_restaurante = new javax.swing.JTextField();
        nivel_restaurante = new javax.swing.JTextField();
        agregar_restaurante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccion_restaurante = new javax.swing.JTextArea();
        entrada_restaurantes = new javax.swing.JComboBox<>();
        salida_restaurante = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        categoria_restaurante = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        calificacion_restaurante = new javax.swing.JSpinner();
        casa = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nombre_casa = new javax.swing.JTextField();
        nivel_casa = new javax.swing.JTextField();
        agregar_casa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        direccion_casa = new javax.swing.JTextArea();
        entrada_casa = new javax.swing.JComboBox<>();
        salida_casa = new javax.swing.JComboBox<>();
        canncahs = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        nombre_canchas = new javax.swing.JTextField();
        nivel_canchas = new javax.swing.JTextField();
        agregar_canchas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        direccion_canchas = new javax.swing.JTextArea();
        entrada_cancha = new javax.swing.JComboBox<>();
        salida_cancha = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        categoria_canchas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        estado_cancha = new javax.swing.JTextField();
        carreteras = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        distancia_carretera = new javax.swing.JTextField();
        numero_carretera = new javax.swing.JTextField();
        jc_inicio = new javax.swing.JComboBox<>();
        jc_final = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tab_lista = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        arbol_general = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_general = new javax.swing.JTable();
        jr_restaurante = new javax.swing.JRadioButton();
        jr_canchas = new javax.swing.JRadioButton();
        jr_carreteras = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lista_general = new javax.swing.JList<>();

        elimiar_restaurante.setText("Eliminar Restaurante");
        elimiar_restaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimiar_restauranteActionPerformed(evt);
            }
        });
        eliminar.add(elimiar_restaurante);

        eliminar_canchas.setText("Eliminar Canchas");
        eliminar_canchas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_canchasActionPerformed(evt);
            }
        });
        eliminar.add(eliminar_canchas);

        eliminar_carreteras.setText("Eliminar Carreteras");
        eliminar_carreteras.setToolTipText("");
        eliminar_carreteras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_carreterasActionPerformed(evt);
            }
        });
        eliminar.add(eliminar_carreteras);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab_lugares.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_lugaresStateChanged(evt);
            }
        });

        jLabel16.setText("Nombre");

        jLabel17.setText("Direccion");

        jLabel18.setText("Nivel de Seguridad");

        jLabel19.setText("Carretera de Entrada");

        jLabel20.setText("Carretera de Salida");

        agregar_restaurante.setText("Agregar");
        agregar_restaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_restauranteActionPerformed(evt);
            }
        });

        direccion_restaurante.setColumns(20);
        direccion_restaurante.setRows(5);
        jScrollPane1.setViewportView(direccion_restaurante);

        jLabel1.setText("Categoria");

        categoria_restaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chino", "Mexicano", "Italiano", "Comida Rapida" }));

        jLabel2.setText("Calificacion");

        calificacion_restaurante.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout restauranteLayout = new javax.swing.GroupLayout(restaurante);
        restaurante.setLayout(restauranteLayout);
        restauranteLayout.setHorizontalGroup(
            restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restauranteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar_restaurante)
                .addGap(285, 285, 285))
            .addGroup(restauranteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(37, 37, 37)
                .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nivel_restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(salida_restaurante, javax.swing.GroupLayout.Alignment.LEADING, 0, 108, Short.MAX_VALUE)
                        .addComponent(entrada_restaurantes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(restauranteLayout.createSequentialGroup()
                        .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(restauranteLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(calificacion_restaurante))
                            .addGroup(restauranteLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(categoria_restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        restauranteLayout.setVerticalGroup(
            restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restauranteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nombre_restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(categoria_restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restauranteLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(restauranteLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(calificacion_restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nivel_restaurante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(entrada_restaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(restauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(salida_restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(agregar_restaurante)
                .addGap(51, 51, 51))
        );

        lugares_tab.addTab("Restaurantes", restaurante);

        jLabel21.setText("Nombre");

        jLabel22.setText("Direccion");

        jLabel23.setText("Nivel de Seguridad");

        jLabel24.setText("Carretera de Entrada");

        jLabel25.setText("Carretera de Salida");

        agregar_casa.setText("Agregar");
        agregar_casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_casaActionPerformed(evt);
            }
        });

        direccion_casa.setColumns(20);
        direccion_casa.setRows(5);
        jScrollPane2.setViewportView(direccion_casa);

        javax.swing.GroupLayout casaLayout = new javax.swing.GroupLayout(casa);
        casa.setLayout(casaLayout);
        casaLayout.setHorizontalGroup(
            casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casaLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(casaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(casaLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(69, 69, 69)
                        .addComponent(nombre_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(casaLayout.createSequentialGroup()
                        .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addGap(30, 30, 30)
                        .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(salida_casa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entrada_casa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nivel_casa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))))
                .addContainerGap(309, Short.MAX_VALUE))
            .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(casaLayout.createSequentialGroup()
                    .addGap(378, 378, 378)
                    .addComponent(agregar_casa)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        casaLayout.setVerticalGroup(
            casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(casaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nombre_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, casaLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, casaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(nivel_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(entrada_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(salida_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(casaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(casaLayout.createSequentialGroup()
                    .addContainerGap(365, Short.MAX_VALUE)
                    .addComponent(agregar_casa)
                    .addGap(34, 34, 34)))
        );

        lugares_tab.addTab("Casas", casa);

        jLabel26.setText("Nombre");

        jLabel27.setText("Direccion");

        jLabel28.setText("Nivel de Seguridad");

        jLabel29.setText("Carretera de Entrada");

        jLabel30.setText("Carretera de Salida");

        agregar_canchas.setText("Agregar");
        agregar_canchas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_canchasActionPerformed(evt);
            }
        });

        direccion_canchas.setColumns(20);
        direccion_canchas.setRows(5);
        jScrollPane3.setViewportView(direccion_canchas);

        entrada_cancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada_canchaActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria");

        categoria_canchas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Football", "Basquet", "Tenis", "Volley" }));

        jLabel4.setText("Estado");

        javax.swing.GroupLayout canncahsLayout = new javax.swing.GroupLayout(canncahs);
        canncahs.setLayout(canncahsLayout);
        canncahsLayout.setHorizontalGroup(
            canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canncahsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(salida_cancha, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entrada_cancha, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nivel_canchas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                    .addGroup(canncahsLayout.createSequentialGroup()
                        .addComponent(nombre_canchas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado_cancha)
                            .addComponent(categoria_canchas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
            .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(canncahsLayout.createSequentialGroup()
                    .addGap(378, 378, 378)
                    .addComponent(agregar_canchas)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        canncahsLayout.setVerticalGroup(
            canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canncahsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(nombre_canchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(categoria_canchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(estado_cancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nivel_canchas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(entrada_cancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salida_cancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(62, 62, 62))
            .addGroup(canncahsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(canncahsLayout.createSequentialGroup()
                    .addContainerGap(365, Short.MAX_VALUE)
                    .addComponent(agregar_canchas)
                    .addGap(34, 34, 34)))
        );

        lugares_tab.addTab("Canchas", canncahs);

        javax.swing.GroupLayout lugaresLayout = new javax.swing.GroupLayout(lugares);
        lugares.setLayout(lugaresLayout);
        lugaresLayout.setHorizontalGroup(
            lugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lugaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lugares_tab)
                .addContainerGap())
        );
        lugaresLayout.setVerticalGroup(
            lugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lugaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lugares_tab)
                .addContainerGap())
        );

        tab_lugares.addTab("Lugares", lugares);

        jLabel5.setText("Numero Unico");

        jLabel6.setText("Distancia");

        jc_inicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel7.setText("Lugar Inicio");

        jLabel8.setText("Lugar Final");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carreterasLayout = new javax.swing.GroupLayout(carreteras);
        carreteras.setLayout(carreterasLayout);
        carreterasLayout.setHorizontalGroup(
            carreterasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreterasLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(carreterasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(carreterasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jc_final, 0, 142, Short.MAX_VALUE)
                    .addComponent(jc_inicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numero_carretera)
                    .addComponent(distancia_carretera))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carreterasLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(301, 301, 301))
        );
        carreterasLayout.setVerticalGroup(
            carreterasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreterasLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(carreterasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numero_carretera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(carreterasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(distancia_carretera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(carreterasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(carreterasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tab_lugares.addTab("Carreteras", carreteras);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_lugares)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_lugares)
                .addContainerGap())
        );

        tab_principal.addTab("Agregar", jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categoria");
        arbol_general.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane7.setViewportView(arbol_general);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tab_lista.addTab("Arboles", jPanel4);

        tabla_general.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_general.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_generalMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabla_general);

        buttonGroup1.add(jr_restaurante);
        jr_restaurante.setSelected(true);
        jr_restaurante.setText("Restaurante");
        jr_restaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_restauranteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jr_canchas);
        jr_canchas.setText("Canchas");
        jr_canchas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_canchasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jr_carreteras);
        jr_carreteras.setText("Carreteras");
        jr_carreteras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_carreterasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jr_restaurante)
                .addGap(100, 100, 100)
                .addComponent(jr_canchas)
                .addGap(77, 77, 77)
                .addComponent(jr_carreteras)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_restaurante)
                    .addComponent(jr_canchas)
                    .addComponent(jr_carreteras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tab_lista.addTab("Tablas", jPanel3);

        jScrollPane5.setViewportView(lista_general);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        tab_lista.addTab("Listas", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_lista)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_lista)
                .addContainerGap())
        );

        tab_principal.addTab("Listar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrada_canchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada_canchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrada_canchaActionPerformed

    private void agregar_restauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_restauranteActionPerformed
        // TODO add your handling code here:
        try {
            nombre = nombre_restaurante.getText();
            direccion = direccion_restaurante.getText();
            nivel_seguridad = Integer.parseInt(nivel_restaurante.getText());
            categoria = (String) categoria_restaurante.getSelectedItem();
            calificacion = (Integer) calificacion_restaurante.getValue();
            restaurantes.add(new Restaurantes(categoria, calificacion, nombre, direccion, nivel_seguridad, new Carretera(), new Carretera()));
            JOptionPane.showMessageDialog(this, "El Restaurante fue agregado");
            
            
            if (Double.parseDouble(distancia_carretera.getText()) <= 50) {
                DefaultListModel modelo = (DefaultListModel) lista_general.getModel();
                modelo.addElement(new Lugares(nombre_restaurante.getText(), direccion_restaurante.getText(), Integer.parseInt(nivel_restaurante.getText()),
                        new Carretera(), new Carretera()));
            }
            
            
            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            Object[] newrow = {nombre_restaurante.getText(), direccion_restaurante.getText(), categoria_restaurante.getSelectedItem(),
                calificacion_restaurante.getValue()};
            modelo.addRow(newrow);
            tabla_general.setModel(modelo);

            DefaultTreeModel m = (DefaultTreeModel) arbol_general.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nodo_lugar;
            nodo_lugar = new DefaultMutableTreeNode(new Lugares(nombre,
                    direccion, nivel_seguridad, new Carretera(), new Carretera()));
            DefaultMutableTreeNode categorias;
            categorias = new DefaultMutableTreeNode(categoria_restaurante.getSelectedItem());
            DefaultMutableTreeNode nombres_restaurante;
            nombres_restaurante = new DefaultMutableTreeNode(this.nombre_restaurante.getText());
            categorias.add(nombres_restaurante);
            nodo_lugar.add(categorias);
            raiz.add(categorias);
            m.reload();
            nombre_restaurante.setText("");
            direccion_restaurante.setText("");
            nivel_restaurante.setText("");
            calificacion_restaurante.setValue(1);
            categoria_restaurante.setSelectedItem(0);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se Puedo Agregar");
        }
    }//GEN-LAST:event_agregar_restauranteActionPerformed

    private void agregar_casaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_casaActionPerformed
        // TODO add your handling code here:
        try {
            nombre = nombre_casa.getText();
            direccion = direccion_casa.getText();
            nivel_seguridad = Integer.parseInt(nivel_casa.getText());
            casas.add(new Casa(nombre, direccion, nivel_seguridad, new Carretera(), new Carretera()));
            JOptionPane.showMessageDialog(this, "La cancha fue agregada ");
            
            if (Double.parseDouble(distancia_carretera.getText()) <= 50) {
                DefaultListModel modelo = (DefaultListModel) lista_general.getModel();
                modelo.addElement(new Lugares(nombre_casa.getText(), direccion_casa.getText(), Integer.parseInt(nivel_casa.getText()),
                        new Carretera(), new Carretera()));
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se Puedo Agregar");
        }
    }//GEN-LAST:event_agregar_casaActionPerformed

    private void agregar_canchasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_canchasActionPerformed
        // TODO add your handling code here:
        try {
            nombre = nombre_canchas.getText();
            direccion = direccion_canchas.getText();
            nivel_seguridad = Integer.parseInt(nivel_canchas.getText());
            estado = estado_cancha.getText();
            categoria = (String) categoria_canchas.getSelectedItem();
            canchas.add(new Canchas(categoria, estado, nombre, direccion, nivel_seguridad, new Carretera(), new Carretera()));
            JOptionPane.showMessageDialog(this, "La cancha fue agregada ");
            
            
            if (Double.parseDouble(distancia_carretera.getText()) <= 50) {
                DefaultListModel modelo = (DefaultListModel) lista_general.getModel();
                modelo.addElement(new Lugares(nombre_canchas.getText(), direccion_canchas.getText(), Integer.parseInt(nivel_canchas.getText()),
                        new Carretera(), new Carretera()));
            }
            
            
            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            Object[] newrow = {nombre_canchas.getText(), direccion_canchas.getText(),
                categoria_restaurante.getSelectedItem()};
            modelo.addRow(newrow);
            tabla_general.setModel(modelo);

            DefaultTreeModel m = (DefaultTreeModel) arbol_general.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode nodo_lugar;
            nodo_lugar = new DefaultMutableTreeNode(new Canchas(categoria,
                    estado, nombre, direccion, nivel_seguridad, new Carretera(), new Carretera()));
            DefaultMutableTreeNode categorias;
            categorias = new DefaultMutableTreeNode(categoria_canchas.getSelectedItem());
            DefaultMutableTreeNode nombres_cancha;
            nombres_cancha = new DefaultMutableTreeNode(nombre_canchas.getText());
            categorias.add(nombres_cancha);
            nodo_lugar.add(categorias);
            raiz.add(categorias);
            m.reload();
            nombre_canchas.setText("");
            direccion_canchas.setText("");
            nivel_canchas.setText("");
            categoria_canchas.setSelectedItem(0);
            estado_cancha.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se Puedo Agregar");
        }
    }//GEN-LAST:event_agregar_canchasActionPerformed

    private void jr_restauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_restauranteActionPerformed
        // TODO add your handling code here
        tabla_general.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Direccion", "Nivel de Seguridad", "Categoria", "Calificacion"
                }) {

        });
        DefaultTableModel model = (DefaultTableModel) tabla_general.getModel();
        for (int i = 0; i < restaurantes.size(); i++) {
            Object[] newrow = {
                restaurantes.get(i).getNombre(),
                restaurantes.get(i).getDireccion(),
                restaurantes.get(i).getNivel_seguridad(),
                restaurantes.get(i).getCatergoria(),
                restaurantes.get(i).getCalificacion()};
            model.addRow(newrow);
        }
        tabla_general.setModel(model);

    }//GEN-LAST:event_jr_restauranteActionPerformed

    private void jr_canchasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_canchasActionPerformed
        // TODO add your handling code here:
        tabla_general.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Direccion", "Nivel de Seguridad", "Categoria", "Estado"
                }) {

        });
        DefaultTableModel model = (DefaultTableModel) tabla_general.getModel();
        for (int i = 0; i < canchas.size(); i++) {
            Object[] newrow = {
                canchas.get(i).getNombre(),
                canchas.get(i).getDireccion(),
                canchas.get(i).getNivel_seguridad(),
                canchas.get(i).getEstado(),
                canchas.get(i).getCategoria()};
            model.addRow(newrow);
        }
        tabla_general.setModel(model);

    }//GEN-LAST:event_jr_canchasActionPerformed

    private void jr_carreterasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_carreterasActionPerformed
        // TODO add your handling code here:
        tabla_general.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Numero", "Distancia"
                }) {

        });
        DefaultTableModel model = (DefaultTableModel) tabla_general.getModel();
        for (int i = 0; i < lista_carretera.size(); i++) {
            Object[] newrow = {
                lista_carretera.get(i).getNumero(),
                lista_carretera.get(i).getKilimetros()};
            model.addRow(newrow);
        }
        tabla_general.setModel(model);

    }//GEN-LAST:event_jr_carreterasActionPerformed

    private void tabla_generalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_generalMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int pp = tabla_general.getSelectedRow();
            eliminar.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tabla_generalMouseClicked

    private void elimiar_restauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimiar_restauranteActionPerformed
        // TODO add your handling code here:
        if (tabla_general.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            restaurantes.remove(tabla_general.getSelectedRow());
            modelo.removeRow(tabla_general.getSelectedRow());

            tabla_general.setModel(modelo);
        }

    }//GEN-LAST:event_elimiar_restauranteActionPerformed

    private void eliminar_canchasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_canchasActionPerformed
        // TODO add your handling code here:
        if (tabla_general.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            canchas.remove(tabla_general.getSelectedRow());
            modelo.removeRow(tabla_general.getSelectedRow());

            tabla_general.setModel(modelo);
        }
    }//GEN-LAST:event_eliminar_canchasActionPerformed

    private void eliminar_carreterasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_carreterasActionPerformed
        // TODO add your handling code here:
        if (tabla_general.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
            lista_carretera.remove(tabla_general.getSelectedRow());
            modelo.removeRow(tabla_general.getSelectedRow());

            tabla_general.setModel(modelo);
        }
    }//GEN-LAST:event_eliminar_carreterasActionPerformed

    private void tab_lugaresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_lugaresStateChanged
        // TODO add your handling code here:
        if (tab_lugares.getSelectedIndex() == 1) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (Object temp : restaurantes) {
                modelo.addElement(temp);
            }
            for (Object temp : casas) {
                modelo.addElement(temp);
            }
            for (Object temp : canchas) {
                modelo.addElement(temp);
            }

            jc_inicio.setModel(modelo);
            jc_final.setModel(modelo);
        }

    }//GEN-LAST:event_tab_lugaresStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        numero = Integer.parseInt(numero_carretera.getText());
        distancia = Double.parseDouble(distancia_carretera.getText());
        inicio = (String) jc_inicio.getSelectedItem();
        finalizacion = (String) jc_final.getSelectedItem();
        lista_carretera.add(new Carretera(new Lugares(), numero, distancia, new Lugares()));
        JOptionPane.showMessageDialog(this, "Carrretera Agregada");
        DefaultTableModel modelo = (DefaultTableModel) tabla_general.getModel();
        Object[] newrow = {nombre_canchas.getText(), direccion_canchas.getText(),
            categoria_restaurante.getSelectedItem()};
        modelo.addRow(newrow);
        tabla_general.setModel(modelo);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_canchas;
    private javax.swing.JButton agregar_casa;
    private javax.swing.JButton agregar_restaurante;
    private javax.swing.JTree arbol_general;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSpinner calificacion_restaurante;
    private javax.swing.JPanel canncahs;
    private javax.swing.JPanel carreteras;
    private javax.swing.JPanel casa;
    private javax.swing.JComboBox<String> categoria_canchas;
    private javax.swing.JComboBox<String> categoria_restaurante;
    private javax.swing.JTextArea direccion_canchas;
    private javax.swing.JTextArea direccion_casa;
    private javax.swing.JTextArea direccion_restaurante;
    private javax.swing.JTextField distancia_carretera;
    private javax.swing.JMenuItem elimiar_restaurante;
    private javax.swing.JPopupMenu eliminar;
    private javax.swing.JMenuItem eliminar_canchas;
    private javax.swing.JMenuItem eliminar_carreteras;
    private javax.swing.JComboBox<String> entrada_cancha;
    private javax.swing.JComboBox<String> entrada_casa;
    private javax.swing.JComboBox<String> entrada_restaurantes;
    private javax.swing.JTextField estado_cancha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JComboBox<String> jc_final;
    private javax.swing.JComboBox<String> jc_inicio;
    private javax.swing.JRadioButton jr_canchas;
    private javax.swing.JRadioButton jr_carreteras;
    private javax.swing.JRadioButton jr_restaurante;
    private javax.swing.JList<String> lista_general;
    private javax.swing.JPanel lugares;
    private javax.swing.JTabbedPane lugares_tab;
    private javax.swing.JTextField nivel_canchas;
    private javax.swing.JTextField nivel_casa;
    private javax.swing.JTextField nivel_restaurante;
    private javax.swing.JTextField nombre_canchas;
    private javax.swing.JTextField nombre_casa;
    private javax.swing.JTextField nombre_restaurante;
    private javax.swing.JTextField numero_carretera;
    private javax.swing.JPanel restaurante;
    private javax.swing.JComboBox<String> salida_cancha;
    private javax.swing.JComboBox<String> salida_casa;
    private javax.swing.JComboBox<String> salida_restaurante;
    private javax.swing.JTabbedPane tab_lista;
    private javax.swing.JTabbedPane tab_lugares;
    private javax.swing.JTabbedPane tab_principal;
    private javax.swing.JTable tabla_general;
    // End of variables declaration//GEN-END:variables
    ArrayList<Carretera> lista_carretera = new ArrayList();
    ArrayList<Restaurantes> restaurantes = new ArrayList();
    ArrayList<Canchas> canchas = new ArrayList();
    ArrayList<Casa> casas = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Lugares lugar_seleccionado;
    String nombre;
    String direccion;
    String estado;
    String categoria;
    int nivel_seguridad;
    int calificacion;
    int numero;
    double distancia;
    String inicio, finalizacion;
}
